import {StyleSheet} from 'react-native';
import {Colors} from "../../assest/colors";
import {scaleSize} from "../../utils/screenUtil";

const style = StyleSheet.create({
    container:{
        flex:1,
    },
    modalStyle:{
        backgroundColor:'#fff',
        flex:1,
        width:WIDTH,
        height:HEIGHT,
        position:'absolute',
        top:0,
        left:0
    },
    renderSectionHeader:{
        width:WIDTH,
        height:35,
        backgroundColor:'#eee',
        justifyContent:'center',
        paddingLeft:8
    },
    renderItem:{
        width:WIDTH,
        height:20,
        marginTop:8,
        marginLeft:8,
        marginBottom:8

    },
    tabItem:{
        justifyContent:'center',
        alignItems:'center',
        borderBottomColor:'red',

    },
    views: {
        height: 50,
        width: WIDTH,
        backgroundColor: 'white',
    },

    scrollView: {
        flex:1,
        backgroundColor: '#EEEEEE',
    },
    bottomView:{
        height:5,
        width:30,
        borderRadius:5,
        position:'absolute',
        bottom:0,
        left:0,
        justifyContent:'center',
        alignItems:'center',

    },
    bottomItem:{
        width:30,
        height:5,
        backgroundColor:'red',
        borderRadius:5
    },
    listItem:{
        width:WIDTH/3-10,
        height:HEIGHT/3-20,
        marginLeft:30/4,
    },
    listItemImage:{
        width:WIDTH/3-10,
        height:HEIGHT/3-60,
        backgroundColor:Colors.defaultColor,
        borderRadius:5,
        marginVertical:5
    },
    listItemTitle:{
        width:WIDTH/3-10,
        fontSize:scaleSize(24),
        color:Colors.textColor
    },
    ratingFinal:{
       position:'absolute',
       bottom:0,
       right:0,
       backgroundColor:'red',
       width:30,
       height:20,
        justifyContent:'center',
        alignItems:'center',
    },
    ratingFinalTitle:{
      color:'#fff',
      fontSize:12
    },
    isIMAX3D:{
        position:'absolute',
        top:0,
        right:0,
        width:60,
        height:20,
        backgroundColor:'rgba(0,0,0,0.5)',
        justifyContent:'center',
        alignItems:'center',
    },
    isIMAX3DTitle:{
      color:'#fff',
      fontSize:10
    },
    isNew:{
        width:scaleSize(50),
        height:scaleSize(60),
        marginLeft:5
    },
    defaultView:{
        flexDirection:'row',
        flexWrap:'wrap',
        marginTop:10
    },
    defaultIndicator:{
        position:'absolute',
        top:0,
        left:0,
        flex:1,
        width:WIDTH,
        height:HEIGHT-100,
        backgroundColor:'transparent',
        justifyContent:'center',
        alignItems:'center',
    },


    defaultItem:{
        width:WIDTH/3-10,
        height:HEIGHT/3-20,
        marginLeft:30/4,
        borderRadius:5
    },
    defaultImage:{
        width:WIDTH/3-10,
        height:HEIGHT/3-60,
        backgroundColor:Colors.defaultColor,
        borderRadius:5,
        marginVertical:5
    },
    defaultBottom:{
        flexDirection:'row',
        width:WIDTH/3-10,
    },
    defaultImageTitle:{
        width:14,
        height:14,
        borderRadius:7,
        backgroundColor:Colors.defaultColor,
        marginHorizontal:5
    },
    defaultTitle:{
        width:WIDTH/3-40,
        height:10,
        backgroundColor:Colors.defaultColor,
        borderRadius:10
    },
    imageView:{
        width:WIDTH/3-10,
        height:HEIGHT/3-60,
        backgroundColor:Colors.defaultColor,
        borderRadius:scaleSize(8),
        marginVertical:5
    },
    movieDetailTopView:{
        width:WIDTH,
        height:HEIGHT/3,
    },
    movieDetailTopView_Bar:{
        width:WIDTH,
        height:HEIGHT/5,
        backgroundColor:Colors.defaultColor,
        flexDirection:'row',
        justifyContent:'space-between'
    },
    movieDetailTopView_Back:{
        width:scaleSize(26),
        height:scaleSize(44),
        marginLeft:10,
        marginTop:25
    },
    movieDetailTopView_Start:{
        width:scaleSize(46),
        height:scaleSize(44),
        marginRight:20,
        marginTop:25
    },
    movieDetailTopView_Image:{
        position:'absolute',
        top:HEIGHT/10+10,
        left:10,
        justifyContent:'center',
        alignItems:'center',
        width:WIDTH/3-10,
        height:HEIGHT/3-60,
        backgroundColor:Colors.movieDetailDefault,
        borderRadius:5
    },
    movieDetailTopView_play:{
        width:scaleSize(60),
        height:scaleSize(60),
    },
    movieDetailTopView_Score:{
        width:50,
        height:50,
        backgroundColor:Colors.movieDetailDefault,
        position:'absolute',
        top:HEIGHT/6,
        right:20,
        justifyContent:'center',
        alignItems:'center',
        borderRadius:2,
        flexDirection:'row'
    },
    movieDetailTopView_Title:{
        width:WIDTH/3,
        height:HEIGHT/9,
        marginLeft:WIDTH/3+10,
        marginTop:0
    },
    movieDetailTop_Title_one:{
        width:WIDTH/3,
        height:10,
        backgroundColor:Colors.defaultColor,
        marginTop:scaleSize(10),
        borderRadius:10

    },
    movieDetailTop_Title_two:{
        width:WIDTH/2,
        height:18,
        marginTop:scaleSize(4),
        //backgroundColor:'red',
        justifyContent:'center'
    },
    runTime:{
        fontSize:scaleSize(22),
        color:Colors.movieText
    },
    location:{
        fontSize:scaleSize(22),
        color:Colors.movieText
    },
    type:{
        fontSize:scaleSize(22),
        color:Colors.movieText,

    },
    commonSpecial:{
        fontSize:scaleSize(25),
        color:'orange'
    },
    movieLabel:{
        flexDirection:'row',
        width:WIDTH/2,
        marginTop:scaleSize(14),
    },
    movieLabelView:{

    },
    movieLabelTitle:{
        fontSize:scaleSize(18),
        color:'red',
        borderWidth:POXEL,
        paddingLeft:5,
        paddingRight:5,
        paddingTop:2,
        paddingBottom:2,
        marginRight:8,
        borderColor:Colors.movieText
    },
    segmentation:{
        width:WIDTH,
        height:scaleSize(25),
        backgroundColor:Colors.defaultColor
    },
    Cell:{
        width:WIDTH,
        height:15,
    },
    storyView:{
        width:WIDTH,
        height:HEIGHT/4,
        marginTop:40
    },
    score:{
        color:'#fff',
        fontSize:18,
        fontWeight:'300',
    },
    movieStoryView:{
        width:WIDTH-40,
        height:10,
        backgroundColor:Colors.defaultColor,
        borderRadius:10,
        marginLeft:20,
        marginTop:10
    },
    movieDetailToolBar:{
        width:WIDTH,
        height:HEIGHT/5,
        flexDirection:'row',
        justifyContent:'space-between',
        backgroundColor:Colors.defaultColor
    },
    topButtonView:{
        flexDirection:'row',
        justifyContent:'space-between',
        backgroundColor:'rgba(0,0,0,0)',
        width:WIDTH,
        height:66,
        position:'absolute',
        top:0,
        left:0
    },
    movieDetailTopBarView:{
        width:WIDTH,
        height:HEIGHT/3+40,
    },

    movieDetailToolBarTitleView:{
        position:'absolute',
        width:WIDTH/3+40,
        height:60,
        top:HEIGHT/10+10,
        left:WIDTH/3+10,
        justifyContent:'center',
        paddingLeft:0
    },
    movieDetailTitleCn:{
        fontSize:scaleSize(33),
        color:'#fff',
        fontWeight:'bold',
        lineHeight:25
    },
    movieDetailTitleEn:{
        fontSize:scaleSize(24),
        color:'#fff',
        lineHeight:25
    },
    plotView:{
        width:WIDTH,
       // justifyContent:'center',
       // alignItems:'center'
    },
    plotContent:{
        fontSize:scaleSize(28),
        color:Colors.movieText,
        paddingLeft:scaleSize(20),
        paddingRight:scaleSize(20),
        paddingTop:scaleSize(20),
        //paddingBottom:scaleSize(25),
        textAlign:'auto',
        fontWeight:'100',
        fontFamily:'Georgia',
        //fontStyle:'italic',
        letterSpacing:3,
        lineHeight:ANDROID?scaleSize(50):0
    },
    openMoreView:{
        width:WIDTH,
        height:30,
        justifyContent:'center',
        alignItems:'center',
        marginTop:10
    },
    openMore:{
        width:scaleSize(30),
        height:scaleSize(30),
    },
    actorView:{
        width:WIDTH,
        height:250,
        paddingTop:20
    },
    actorItemView:{
        width: WIDTH/3,
        height: 200,
        alignItems:'center'
    },
    actorItemImage:{
        width: WIDTH/3,
        height: 160,
        elevation: 6,
        shadowOffset: {width: 0, height: 0},
        shadowColor: 'black',
        shadowOpacity: 1,
        shadowRadius: 5
    },
    actorItemTitle:{
        fontSize:scaleSize(20),
    },
    moreActorView:{
        position:'absolute',
        top:10,
        right:20,

    },
    moreActorViewTitle:{
        fontSize:scaleSize(24),
        color:Colors.activeTintColor
    },
    movieDetailsVideoView:{
        width:WIDTH,

    }
});

export {
    style
}