import {StyleSheet} from 'react-native';
import {Colors} from "../../assest/colors";
import {scaleSize,ifIphoneX} from "../../utils/screenUtil";

const style = StyleSheet.create({

    container:{
        flex:1,
        backgroundColor:'#fff'
    },
    container1:{
        flex:1,
        backgroundColor:'#fff',
        flexDirection:'row',
    },

    leftScrollView:{
        width:60,
        justifyContent:'center'
    },

    leftArrayView:{
        width:60,
        height:50,
        justifyContent:'center',
        alignItems:'center',
        flexDirection:'row'
    },
    indicator:{
      width:2,
      height:20,
      backgroundColor:'red',
      position:'absolute',
        left:6,
        top:15

    },
    indicator1:{
        width:20,
        height:scaleSize(5),
        borderRadius:scaleSize(5),
        backgroundColor:'red',
        position:'absolute',
        left:WIDTH/8+5,
        bottom:0

    },
    indicatorView:{
      width:10,
      height:20,
      position:'absolute',
      right:5,
      top:15,
        backgroundColor:'red'
    },

    renderSectionHeader:{
        width:WIDTH-60,
        height:40,
        justifyContent:'center',
        alignItems:'center',
        backgroundColor:'#fff',
        flexDirection:'row'
    },
    new_buy_star_bg:{
        width:  scaleSize(17),
        height:scaleSize(16)
    },
    renderSectionHeaderTitle:{
        color:Colors.movieText,
        marginHorizontal:18
    },
    new_buy_star_bg_cell:{
        height:POXEL,
        backgroundColor:'#e4e4e4',
        width:WIDTH/4,
        marginHorizontal:10
    },
    renderItemTitle:{
         width:WIDTH/3 +20,
         height:80,
         borderRadius:5,
         flexDirection:'row',
         alignItems:'center',
         backgroundColor:Colors.bookColor,
         marginLeft:10,
         marginBottom:10

    },
    itemTitle:{
        marginBottom:5
    },
    bookCount:{
     fontSize:10,
        color:Colors.movieText
    },
    ItemView:{
        marginLeft:10,
        //marginRight:15
    },
    bookItemImg:{
        position:'absolute',
        flexDirection:'row',
        width:WIDTH/5-10,
        alignItems:'flex-end',
        right:0,
        bottom:0,
    },
    bookItemImgView:{
        position:'absolute',
        bottom:0,
        width:42,
        height:60,
        zIndex:99,
        left:9
    },
    bookItemImgView1:{
        width:32,
        height:50
    },
    bookItemImgView2:{
        width:28,
        height:46
    },
    ListFooterComponent:{
        width:WIDTH,
        height:170,
        justifyContent:'center',
       // alignItems:'center',
        marginLeft:WIDTH/2/2
    },
    ListFooterComponentTitle:{
        color:Colors.movieText,

    },
    classListViewTopView:{
        width:WIDTH,
        height:scaleSize(160),
        borderBottomWidth:scaleSize(1),
        borderBottomColor:Colors.borderColor,
        backgroundColor:Colors.headerBarColor,
    },
    leftTypeView:{
        width:WIDTH/6,
        height:25,
        justifyContent:'center',
        alignItems:'center',
        borderRadius:25
    },
    chooseView:{
        width:WIDTH/6,
        height:40,
        position:'absolute',
        top:0,
        left:0,
        borderRadius:20,
        borderColor:'red',
        borderWidth:POXEL

    },
    divider:{
        width:WIDTH-40,
        height:scaleSize(1),
        backgroundColor:Colors.borderColor,
        marginLeft:15
    },
    drop_down_title:{
        fontSize:scaleSize(23),
        color:Colors.movieText,
    },
    lineView:{
        height:scaleSize(40),
        width:scaleSize(1),
        backgroundColor:Colors.borderColor
    },
    rightMinorView:{
        flex:1,
        width:WIDTH/2,
        height:40,
        justifyContent:'center',
        alignItems:'center',
        flexDirection:'row'
    },
    bookLoadView:{
        width:WIDTH,
        height:scaleSize(280),
        //backgroundColor:'red',
        flexDirection:'row',
        alignItems:'center'
    },
    leftBookView:{
        width:scaleSize(140),
        height:scaleSize(200),
        backgroundColor:Colors.defaultColor,
        borderRadius:5,
        marginLeft:20,
        shadowOffset: {width: 0, height: 0},
        shadowColor: Colors.defaultColor,
        shadowOpacity: 1,
        shadowRadius: 5,
        elevation: 10,
    },
    rightBookView:{
        marginLeft:20,
        justifyContent:'flex-end',
        height:110,
        width:WIDTH-(82+20+20+20),
    },
    rightBookViewTitle:{
        width:60,
        height:10,
        backgroundColor:Colors.defaultColor,
        marginTop:10,
        borderRadius:10
    },
    bookLoadBottomView:{
        width:WIDTH-60,
        height:POXEL,
        backgroundColor:Colors.borderColor,
        position:'absolute',
        bottom:0,
        right:30
    },
    loadingMore:{
        width:WIDTH,
        height:40,
        justifyContent:'center',
        alignItems:'center',
        flexDirection:'row'
    },
    loadingView:{
        width:WIDTH,
        height:HEIGHT-scaleSize(300),
        justifyContent:'center',
        alignItems:'center',
        position:'absolute',
        top:0,
        left:0,
        zIndex:99,
        overflow:'hidden'
    },
    BookViewTitle:{
        fontSize: IOS? 17 : 18,
        fontWeight: IOS ? '700' : '500',
        color: 'rgba(0, 0, 0, .9)',
    },
    BookViewContext:{
        fontSize:scaleSize(21),
        color:Colors.movieText,
        lineHeight:20,
        marginBottom:10,
        marginTop:10
    },
    latelyFollower:{
        fontSize:scaleSize(21),
        color:'red',
        lineHeight:20
    },
    retentionRatio:{
        fontSize:scaleSize(21),
        color:Colors.movieText,
        lineHeight:20
    },
    bookDetailViewTop:{
        width:WIDTH,
        height:HEIGHT/3,
        flexDirection:'row',
        alignItems:'center'
    },
    bookDetailViewTopLeftImg:{
        width:scaleSize(210),
        height:scaleSize(300),
        backgroundColor:Colors.defaultColor,
        borderRadius:5,
        marginLeft:scaleSize(44)
    },
    bookDetailViewTopTextView:{
        width:WIDTH/2,
        height:scaleSize(300),
        marginLeft:scaleSize(44)
    },
    bookDetailViewTopRight:{
        width:WIDTH/2,
        height:10,
        backgroundColor:Colors.defaultColor,
        borderRadius:10,
        marginTop:5
    },
    bookDetailViewTopTitleRight:{
        width:WIDTH/2,
        fontSize: 20,
        fontWeight: IOS ? '700' : '500',
        color: 'rgba(0, 0, 0, .9)',
    },

    scoreLeft:{
        width:60,
        height:10,
        backgroundColor:Colors.defaultColor,
        borderRadius:10,
        marginRight:10
    },
    scoreLeftTitle:{
        fontSize:20,
        fontWeight: IOS ? '700' : '500',
        color:'orange',
        marginRight:10
    },
    score:{
        width:scaleSize(40),
        height:scaleSize(40),
    },
    startStyle:{
        width:scaleSize(40),
        height:scaleSize(40),
    },
    bookDetailViewBottomView:{
        width:WIDTH,
        height:80,
        flexDirection:'row',
        justifyContent:'center',

    },
    bookDetailViewBottomTitle:{
        //width:(WIDTH-60)/4,
        height:30,
        justifyContent:'center',
        alignItems:'center',
        width:80,


    },
    bookDetailViewBottomTitleStyle:{
        fontSize:14,
        color:Colors.movieText,
    },
    IntroductionView:{
        width:WIDTH,
    },
    IntroductionTitle:{
        fontSize: IOS? 20 : 20,
        fontWeight: IOS ? '700' : '500',
        color: 'rgba(0, 0, 0, .9)',
        marginLeft:30,
        marginTop:30,
        marginBottom:10
    },
    IntroductionViewItem:{
        width:WIDTH-60,
        height:10,
        backgroundColor:Colors.defaultColor,
        borderRadius:10,
        marginLeft:30,
        marginTop:15
    },
    bookBottomView:{
        position:'absolute',
        bottom:0,
        left:0,
        width:WIDTH,
        flexDirection:'row',
       borderTopWidth:POXEL,
        borderTopColor:Colors.defaultColor,
        backgroundColor:'rgba(255,255,255,0.9)',
        ...ifIphoneX({
            height:80
        },{
            height:60,
        }),

    },
    ChaseView:{
        width:WIDTH/2,
        height:60,
        justifyContent:'center',
        alignItems:'center'
    },
    dotChaseView:{
        width:WIDTH/2-30,
        height:40,
        justifyContent:'center',
        alignItems:'center',
        backgroundColor:Colors.defaultColor,
        borderRadius:40
    },
    dotChaseTitle:{
        color:'red',
        fontSize:18,
        fontWeight:'500'
    },
    authorView:{
        fontSize:16,
        color:'red'
    },
    authorImage:{
        width:scaleSize(25),
        height:scaleSize(25),
        marginRight:10
    },
    majorCate:{
        fontSize:16,
        color:Colors.movieText
    },
    wordCount:{
        fontSize:16,
        color:Colors.movieText
    },
    wordCount1:{
        fontSize:12,
        color:Colors.movieText
    },
    longIntroView:{
        width:WIDTH,
        justifyContent:'center',
        alignItems:'center',
        marginBottom:15
    },
    longIntro:{
        fontSize:16,
        color:Colors.textColor,
        width:WIDTH-60,
        lineHeight:30,
        marginTop:15
    },
    recommendedView:{
        width:WIDTH,
        alignItems:'center',
        justifyContent:'center',
        marginTop:20
    },
    recommended:{
        width:WIDTH-40,
        backgroundColor:'#F0F0F5',
        alignItems:'center',
        borderRadius:5,
    },
    recommendedTitle:{
        fontSize:20,
        fontWeight:'400',
        color:Colors.movieText,
        marginTop:20
    },
    recommendedContext:{
        fontSize:15,
        lineHeight:25,
        width:WIDTH-80,
        color:Colors.textColor,
        marginTop:10,
        marginBottom:20
    },
    evaluationView:{
        width:WIDTH,
    },
    evaluationItemView:{
        width:WIDTH,
        backgroundColor:'#fff'
    },
    evaluationItemTopView:{
        flexDirection:'row',
        width:WIDTH,
        alignItems:'center',
        justifyContent:'space-between',
        paddingTop:20
    },
    evaluationItemImageView:{
        width:scaleSize(60),
        height:scaleSize(60),
        backgroundColor:Colors.defaultColor,
        borderRadius:scaleSize(30),
        marginRight:15
    },
    avatarTitle:{
        color:Colors.movieText,
        fontSize:15,
        marginRight:10
    },
    avatarLvView:{
        borderWidth:POXEL,
        borderColor:Colors.movieText,
        width:32,
        height:12,
        justifyContent:'center',
        alignItems:'center',
        borderRadius:15

    },
    avatarLvView1:{
        borderWidth:POXEL,
        borderColor:Colors.movieText,
        width:35,
        height:15,
        justifyContent:'center',
        alignItems:'center',
        borderRadius:15

    },
    avatarLv:{
        color:Colors.movieText,
        fontSize:10,
    },
    avatarContentView:{
        justifyContent:'center',
        alignItems:'center',
        width:WIDTH,
        marginTop:20
    },
    avatarContent:{
        fontSize:14,
        color:Colors.textColor,
        lineHeight:20,
        width:WIDTH-60
    },
    praise:{
        width:scaleSize(23),
        height:scaleSize(23),
        marginRight:10
    },
    allEvaluation:{
        width:WIDTH,
        height:scaleSize(150),
        justifyContent:'center',
        alignItems:'center',
    },
    evaluation_total:{
        fontSize:15,
        color:'red'
    },
    recommend_image:{
        width:scaleSize(180),
        height:scaleSize(240),
        backgroundColor:Colors.defaultColor,
        borderRadius:5,
        marginBottom:8,
        marginTop:20
    },
    recommend_book:{
        width:WIDTH/3-10,
        justifyContent:'center',
        alignItems:'center',
    },
    lookMoreView:{
        position:'absolute',
        right:30,
    },
    evaluationViewTitle:{
        fontSize: IOS? 20 : 20,
        fontWeight: IOS ? '700' : '500',
        color: 'rgba(0, 0, 0, .9)',
        marginLeft:30
    },
    lookMoreTitle:{
        color:Colors.movieText,
        fontSize:14
    },
    copyright:{
        color:Colors.movieText,
        fontSize:17,
    },
    bookCommentsTopView:{
        width:WIDTH,
        height:HEIGHT/5,
        backgroundColor:Colors.headerBarColor,
        flexDirection:'row',
        alignItems:'center',

    },
    bookCommentsTopLeftImg:{
        width:scaleSize(140),
        height:scaleSize(200),
        backgroundColor:Colors.defaultColor,
        borderRadius:5,
        marginLeft:scaleSize(44)
    },
    bookCommentsTopTextView:{
        width:WIDTH/2,
        height:scaleSize(240),
        marginLeft:scaleSize(44)
    },
    collectionView:{
        width:80,
        height:30,
        backgroundColor:Colors.defaultColor,
        borderRadius:30,
        justifyContent:'center',
        alignItems:'center',
        position:'absolute',
        right:20,
        top:20
    },
    bookCommentsTabView:{
        width:WIDTH,
        height:40,
        backgroundColor:Colors.headerBarColor,
        justifyContent:'space-around',
        flexDirection:'row',
        alignItems:'center',
        borderBottomWidth:POXEL,
        borderBottomColor:Colors.headerBottomColor
    },

    bookCommentsTabTitle:{

        fontSize:14
    },
    bookCommentsItemView:{
        width:WIDTH
    },
    bookCommentsItem:{
        width:WIDTH,
        height:100,
        marginTop:20,
    },

    bookCommentsItemBottom:{
        flexDirection:'row',
        alignItems:'center',
        marginLeft:20,
    },
    bookCommentsItemBottomLeftImage:{
        width:scaleSize(110),
        height:scaleSize(110),
        backgroundColor:Colors.defaultColor,
        borderRadius:30,
        marginRight:15
    },
    bookCommentsItemRight:{
        width:WIDTH/2,
        height:10,
        borderRadius:10,
        backgroundColor:Colors.defaultColor,
        marginVertical:5
    },
    commentTopView:{
        width:WIDTH,
        height:60,
        backgroundColor:'#fff',
        alignItems:'center',
        flexDirection:'row',
        borderBottomWidth:POXEL,
        borderBottomColor:Colors.defaultColor
    },
    commentTopViewLeft:{
        width:scaleSize(40),
        height:scaleSize(40),
        marginLeft:scaleSize(44),
        marginRight:10,
    },
    commentTopViewLeft1:{
        width:scaleSize(25),
        height:scaleSize(25),
        marginRight:5,
    },
    commentTopViewRight:{
        fontSize:13,
        color:Colors.movieText,
        fontWeight:'400'
    },
    bookReviewScreenView:{
        width:WIDTH,
        justifyContent:'center',
        height:120,
        paddingLeft:scaleSize(44),
        paddingRight:scaleSize(44),
        backgroundColor:'#fff'
    },
    bookReviewScreenViewBottom:{
        flexDirection:'row',
        marginTop:10,
    },
    itemSeparatorComponent:{
        width:WIDTH,
        height:2,
        justifyContent:'center',
        alignItems:'center'
    },
    bookReviewScreenViewTitle:{
        fontSize: 16,
        fontWeight: IOS ? '400' : '400',
        color: 'rgba(0, 0, 0, .9)',
        lineHeight:30
    },
    nickname:{
        fontSize: 12,
        marginBottom:5,
        marginRight:scaleSize(24),
        color:'rgba(0, 0, 0, .8)',
    },
    bookReviewScreenViewRight:{
        flexDirection:'row',
        position:'absolute',
        right:20,
        bottom:0,
        height:40,
        alignItems:'center'
    },
    bookReviewScreenContent:{
        fontSize:15,
        color:Colors.movieText,
        lineHeight:25
    },
    ratingView:{
        position:'absolute',
        right:100,
    },
    tabView:{
        width:WIDTH/3,
        height:40,
        justifyContent:'center',
        alignItems:'center',
    },
    bookCommentPerTopTitle:{
        fontSize: 20,
        fontWeight: IOS ? '700' : '500',
        color: 'rgba(0, 0, 0, .9)',
    },
    bookCommentPerBottom:{
        width:WIDTH-40,
        height:140,
        backgroundColor:Colors.defaultColor,
        borderRadius:5,
        alignItems:'center',
        marginTop:20,
        flexDirection:'row'
    },
    commentsView:{
        width:WIDTH,
        height:ANDROID?60:50,
        backgroundColor:'rgba(255,255,255,255)',
        position:'absolute',
        bottom:0,
        left:0,
        borderTopWidth:POXEL,
        borderTopColor:Colors.borderColor,
        flexDirection:'row',
        alignItems:'center'

    },
    chapter_review_send:{
        width:scaleSize(52),
        height:scaleSize(52),
        marginLeft:20
    },
    sendView:{
        width:50,
        height:30,
        borderRadius:40,
        backgroundColor:'red',
        justifyContent:'center',
        alignItems:'center'
    }

});

export {
    style
}